#! /usr/bin/env php

<?php

use Gitpi\Commands\RunCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$app = new Application('gitPi', '0.1');

$app->add(new RunCommand);

$app->run();